### ISSUE TITLE
【BUG】主播已下播，没有下播通知，直播计时器依然在计时

### ISSUE THREAD

**Issue by lin6953** [djkcyl/BBot-Graia#76]
![a6389c815ec36a92276c843195cf330e](https://github.com/djkcyl/BBot-Graia/assets/107689301/19d801c7-5065-4944-9299-7f03409decb8)
![fe2d6e1b4a8ec1f846fe5b8111114913](https://github.com/djkcyl/BBot-Graia/assets/107689301/f0c6b5b8-b578-464a-b4d9-a6846fda61b9)

**Comment by Well2333** [comment]
可能是由于每天0点刷新token后导致直播刷新器死锁导致的
